### ISSUE TITLE
transactions on window not working 

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/pixl-server-storage#3]
I did some tweaks to Cronicle to make it work on Windows (and it works indeed).

But I noticed if storage transaction feature is enabled, it's not working properly.

The reason is that on Windows directories cannot be opened as files. Perhaps flushing directory is not necessary on Windows (I couldn't find any info on flushing dirs ). 

Issues are coming from this function
https://github.com/jhuckaby/pixl-server-storage/blob/master/transaction.js#L737

Suggestion - add OS check, and if it's windows - return immediately (without doing folder fsync).

**Comment by jhuckaby** [comment]
Hey Mike!

Honestly, I'm surprised this is the *only* issue with running pixl-server-storage on Windows.  I kind of amazed it actually works.

So yeah, transactions are really a Linux/macOS thing, as they use fsync.  I can't imagine that ever working properly on Windows.

What I mean is, trying to do transactions *at all* is kind of a waste on Windows, because I doubt recovery (rollback, etc.) would actually work as intended.

So, before I add a Windows-specific hack (🤮) to skip the directory fsync, let me just ask, can you not just disable storage transactions entirely for your Windows version of Cronicle?  It's in the Cronicle config file here:

https://github.com/jhuckaby/Cronicle/blob/master/sample_conf/config.json#L78

All I did in the latest Cronicle release was default this to `true`.

Just set that property to `false`, and everything should go back to the way it was.

Is that a viable solution for you?  I am trying to avoid adding hacks to the code for Windows, as I really, deeply despise that OS, and the presence of such a hack also implies that I support Windows in the code, which I do not.

**Comment by jhuckaby** [comment]
I made it work without calling out Windows specifically 😊 .  I just made the `fs.open` on the dir a non-fatal error, so it'll just skip the dir fsync.  [Commit Diff](https://github.com/jhuckaby/pixl-server-storage/commit/88fa3b4c11d5813c5692146e6bdbe9ab4dd2354a#diff-c8a17dca3be0ba9c17f78c04e4da896c555c6119b329a0e6066e89aac91b77cd)

Published [v3.1.12](https://github.com/jhuckaby/pixl-server-storage/releases/tag/v3.1.12) with a fix for this, among some other misc fixes.

**Comment by mikeTWC1984** [comment]
Yes,  it did work, and disabling transaction fix the issue. 
The latest commit fixes the problem for the transaction mechanism, thanks. 
But there is still one more quirk with Filesystem engine. When transaction is enable, the "sync" method is called:
https://github.com/jhuckaby/pixl-server-storage/blob/master/engines/Filesystem.js#L632
It also uses fsync, but on Windows fsync doesn't work in read only ("r")  mode. I guess for Windows that should be "r+" (read/write). I guess that's not a big deal anyway (could be patched locally)

**Comment by jhuckaby** [comment]
Ah, I figured there was another shoe waiting to drop.  That's what I meant by my initial comment above ("honestly I'm surprised this is the *only* issue with running pixl-server-storage on Windows").

I can't help but feel that this is all for naught anyway, because I would eat my hat if Windows could actually handle a sudden power loss in the middle of a transaction and actually do the recovery operation using an fsync'ed transaction rollback log.

I guess what I am saying is, I think transactions should just be entirely disabled on Windows.  They aren't buying you anything, and honestly they are likely slowing things down, with all the extra filesystem calls needed (Windows FS layer is garbage).

Anyway, if you are okay with just disabling transactions on your Windows Cronicle install, then I'm cool with just leaving this as is.  I feel dirty adding more hacks.

**Comment by mikeTWC1984** [comment]
Yeah, that's just pure experiment. I'll just use a bit patched FS Engine. The other problem with Windows I discovered that it doesn't really send same kind on signal as unix on termination. More over if process runs on the background it cannot be killed gracefully (without some hacks), so I guess transaction might somewhat helpful.
Btw, one of the few signals node process can catch in Windows is sighup (closing terminal). I noticed that pixl-server does not listen for it (only sigint/sigterm), so in case cronicle runs in terminal the shutdown processes won't be triggered (on closing terminal), even on linux.

**Comment by jhuckaby** [comment]
> Btw, one of the few signals node process can catch in Windows is sighup (closing terminal). I noticed that pixl-server does not listen for it (only sigint/sigterm), so in case cronicle runs in terminal the shutdown processes won't be triggered (on closing terminal), even on linux.

Holy crap, I never knew this.  Thank you so much for telling me.  I honestly always thought SIGHUP was a manual signal you had to send by hand, as a way to tell a process to restart itself (Apache does this I believe).  I had no idea a closing terminal window sent it.

I'll add this listener to pixl-server right away.  Thank you!

**Comment by jhuckaby** [comment]
https://github.com/jhuckaby/pixl-server/commit/ee2ce31a991a459ce447de0a3efa963f22fd6802
